apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations :
 #   metallb.universe.tf/address-pool : default
    metallb.universe.tf/allow-shared-ip : shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
    protocol: TCP
  - port: 21000
    targetPort: 21000
    name: ftps-data
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: service_ftps
        imagePullPolicy: Never